name: Notify deployment

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # deployment permission
      pages: write
      id-token: write
      # issue creation permission
      issues: write
      contents: read
    steps:
    - uses: actions/checkout@v6
    - uses: taiki-e/install-action@v2
      with:
        tool: mdbook,mdbook-mermaid

    - name: Link Checker
      id: lychee
      uses: lycheeverse/lychee-action@v2
      with:
        fail: false
        workingDirectory: src

    - name: Create Issue From File
      if: steps.lychee.outputs.exit_code != 0
      uses: peter-evans/create-issue-from-file@v5
      with:
        title: Link Checker Report
        content-filepath: src/lychee/out.md
        labels: report, automated issue

    - run: mdbook build
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: book
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check the url availability
      env:
        URL: https://os-checker.github.io/gh-repository_dispatch/
      run: |
        for i in {1..5}; do
          status=$(curl -L -o /dev/null -w "%{http_code}" $URL)
          echo "$URL status $status"
          if [ "$status" == "200" ]; then exit 0; fi
          sleep 30
        done
        exit 1
    - name: Notify Main Repo
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }} # 需要一个具有代码仓库写入权限的 Personal Access Token
        repository: os-checker/gh-repository_dispatch      # 代码仓库名
        event-type: docs_deployed       # 自定义事件名称
        client-payload: '{"version": "1"}' # 也可以传版本号过去
